/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author joelr
 */
public class frmBoleto extends javax.swing.JFrame {
    int numPelicula;
    /**
     * Crea el form frmFuncion
     * Pide un atributo int para mostrar los datos de la pelicula elegida.
     */
    public frmBoleto(int pelicula) {
        initComponents();
        posterPelicula(pelicula);
        numPelicula=pelicula;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelBarraCinepolis = new javax.swing.JPanel();
        jLabelCinepolis = new javax.swing.JLabel();
        jLabelBoleto = new javax.swing.JLabel();
        jLabelPelicula = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jLabelBoleto1 = new javax.swing.JLabel();
        jButtonComprarOtro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        PanelFondo.setBackground(new java.awt.Color(0, 0, 0));
        PanelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFondo.setPreferredSize(new java.awt.Dimension(600, 600));

        PanelBarraCinepolis.setBackground(new java.awt.Color(51, 51, 255));

        jLabelCinepolis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCinepolis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosPresentacion/IconCinepolis2.png"))); // NOI18N
        jLabelCinepolis.setText("jLabel1");

        jLabelBoleto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelBoleto.setForeground(new java.awt.Color(255, 255, 0));
        jLabelBoleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoleto.setText("Boleto");

        javax.swing.GroupLayout PanelBarraCinepolisLayout = new javax.swing.GroupLayout(PanelBarraCinepolis);
        PanelBarraCinepolis.setLayout(PanelBarraCinepolisLayout);
        PanelBarraCinepolisLayout.setHorizontalGroup(
            PanelBarraCinepolisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraCinepolisLayout.createSequentialGroup()
                .addComponent(jLabelCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jLabelBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBarraCinepolisLayout.setVerticalGroup(
            PanelBarraCinepolisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraCinepolisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBoleto)
                .addGap(17, 17, 17))
        );

        jLabelPelicula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosPresentacion/Deadpool3.jpg"))); // NOI18N
        jLabelPelicula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("Volver a Inicio");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelBoleto1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelBoleto1.setForeground(new java.awt.Color(255, 255, 0));
        jLabelBoleto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoleto1.setText("Muchas Gracias por su compra");

        jButtonComprarOtro.setBackground(new java.awt.Color(0, 51, 153));
        jButtonComprarOtro.setForeground(new java.awt.Color(255, 255, 0));
        jButtonComprarOtro.setText("Comprar Otro Boleto");
        jButtonComprarOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarOtroActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Ver Boleto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBarraCinepolis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBoleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonComprarOtro)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVolver))))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelBarraCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelBoleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonComprarOtro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVolver))
                    .addComponent(jLabelPelicula))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        frmPantallaPrincipal p = new frmPantallaPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonComprarOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarOtroActionPerformed
        frmFuncion f = new frmFuncion(numPelicula);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonComprarOtroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
/* 
 * Metodo para elegir el poster de la pelicula en base de la pelicula elegida por el usuario.
 */
public void posterPelicula(int pelicula){
    Icon imagen;
    switch(pelicula){
        case 1: //Harry Potter 1
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/HarryPotter1.jpg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
        case 2:// Harry Potter 2
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/HarryPotter2.jpeg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
        case 3:// Harry Potter 3
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/HarryPotter3.jpg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
        case 4:// Deadpool & Wolverine
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/Deadpool3.jpg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
        case 5:// Transformers One
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/TransformersOne.jpg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
        case 6:// Beetlejuice Beetlejuice
        imagen= new ImageIcon(getClass().getResource("/recursosPresentacion/bettlejuice2.jpg"));
        this.jLabelPelicula.setIcon(imagen);
        break;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBarraCinepolis;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonComprarOtro;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelBoleto;
    private javax.swing.JLabel jLabelBoleto1;
    private javax.swing.JLabel jLabelCinepolis;
    private javax.swing.JLabel jLabelPelicula;
    // End of variables declaration//GEN-END:variables
}
