/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author joelr
 */
public class frmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmPantallaPrincipal
     */
    public frmMenuAdmin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelBarraCinepolis = new javax.swing.JPanel();
        jLabelCinepolis = new javax.swing.JLabel();
        jLabelConfigAdmin = new javax.swing.JLabel();
        jButtonVerPeliculas = new javax.swing.JButton();
        jButtonVerFunciones = new javax.swing.JButton();
        jLabelConfigAdmin1 = new javax.swing.JLabel();
        jLabelConfigAdmin2 = new javax.swing.JLabel();
        jLabelConfigAdmin3 = new javax.swing.JLabel();
        jButtonVerUsuarios = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        PanelFondo.setBackground(new java.awt.Color(0, 0, 0));
        PanelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFondo.setPreferredSize(new java.awt.Dimension(600, 600));

        PanelBarraCinepolis.setBackground(new java.awt.Color(51, 51, 255));

        jLabelCinepolis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCinepolis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosPresentacion/IconCinepolis2.png"))); // NOI18N
        jLabelCinepolis.setText("jLabel1");

        jLabelConfigAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelConfigAdmin.setForeground(new java.awt.Color(255, 255, 0));
        jLabelConfigAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfigAdmin.setText("Configuracion Administrador");

        javax.swing.GroupLayout PanelBarraCinepolisLayout = new javax.swing.GroupLayout(PanelBarraCinepolis);
        PanelBarraCinepolis.setLayout(PanelBarraCinepolisLayout);
        PanelBarraCinepolisLayout.setHorizontalGroup(
            PanelBarraCinepolisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraCinepolisLayout.createSequentialGroup()
                .addComponent(jLabelCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConfigAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBarraCinepolisLayout.setVerticalGroup(
            PanelBarraCinepolisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraCinepolisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConfigAdmin)
                .addGap(15, 15, 15))
        );

        jButtonVerPeliculas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVerPeliculas.setForeground(new java.awt.Color(255, 255, 0));
        jButtonVerPeliculas.setText("Modificar Peliculas");

        jButtonVerFunciones.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVerFunciones.setForeground(new java.awt.Color(255, 255, 0));
        jButtonVerFunciones.setText("Modificar Funciones");

        jLabelConfigAdmin1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelConfigAdmin1.setForeground(new java.awt.Color(255, 255, 0));
        jLabelConfigAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfigAdmin1.setText("Peliculas");

        jLabelConfigAdmin2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelConfigAdmin2.setForeground(new java.awt.Color(255, 255, 0));
        jLabelConfigAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfigAdmin2.setText("Usuarios");

        jLabelConfigAdmin3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelConfigAdmin3.setForeground(new java.awt.Color(255, 255, 0));
        jLabelConfigAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfigAdmin3.setText("Funciones");

        jButtonVerUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVerUsuarios.setForeground(new java.awt.Color(255, 255, 0));
        jButtonVerUsuarios.setText("Modificar Usuarios");

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBarraCinepolis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabelConfigAdmin1))
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButtonVerPeliculas)))
                        .addGap(34, 34, 34)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addComponent(jLabelConfigAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFondoLayout.createSequentialGroup()
                                .addComponent(jButtonVerUsuarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVerFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelConfigAdmin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelBarraCinepolis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfigAdmin1)
                    .addComponent(jLabelConfigAdmin2)
                    .addComponent(jLabelConfigAdmin3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerFunciones)
                    .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVerUsuarios)
                        .addComponent(jButtonVerPeliculas)))
                .addGap(29, 29, 29)
                .addComponent(jButtonSalir)
                .addContainerGap(546, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBarraCinepolis;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerFunciones;
    private javax.swing.JButton jButtonVerPeliculas;
    private javax.swing.JButton jButtonVerUsuarios;
    private javax.swing.JLabel jLabelCinepolis;
    private javax.swing.JLabel jLabelConfigAdmin;
    private javax.swing.JLabel jLabelConfigAdmin1;
    private javax.swing.JLabel jLabelConfigAdmin2;
    private javax.swing.JLabel jLabelConfigAdmin3;
    // End of variables declaration//GEN-END:variables
}
